export const TOTAL_WISHLIST = 'TOTAL_WISHLIST';
export const TOTAL_WISHLIST_INTIME = 'TOTAL_WISHLIST_INTIME';
export const GET_SETTING = 'GET_SETTING';
export const UPDATE_SETTING = 'UPDATE_SETTING';
export const LOADING_SETTING = 'LOADING_SETTING';